### ISSUE TITLE
Create System

### ISSUE THREAD

**Issue by RouNNdeL** [APRO-Project/lab0#5]
The `System` class has to include following methods: 
- `insertTicket(Ticket ticket) -> int id`
- `updateTicket(int id, Ticket ticket) -> boolean`
- `createUser(User user) -> int id`
- `updateUser(int id, User user) -> boolean`
- `getAllTickets() -> List<Ticket>` (sort by id)
- `getTicketsSortByPriority(bool reverseOrder = false) -> List<Ticket>`
- `getTicketsSortByLocation(bool reverseOrder = false) -> List<Ticket>`
- ~`getTicketsForUser(int userId) ->  List<Ticket>`~

**Comment by BWalusiak** [comment]
done

**Comment by RouNNdeL** [comment]
There should be 3 separate methods for getting `Tickets` for a specific user: 
- `getTicketsForConsumer(int userId) -> List<Ticket>`
- `getTicketsForDispatcher(int userId) -> List<Ticket>`
- `getTicketsForContractor(int userId) -> List<Ticket>`
